import React, { useState } from "react";
import axios from "axios";

const Register = () => {
  const [user, setUser] = useState({
    userId: "",
    userEmail: "",
    userName: "",
    userPhone: "",
    userPassword: "",
  });

  const handleChange = (e) => {
    setUser({
      ...user,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Sending userId is optional if it's auto-generated by the backend
    const { userId, ...userData } = user;

    axios
      .post("http://localhost:8080/api/register", userData)
      .then((response) => {
        alert(response.data);
      })
      .catch((error) => {
        alert("Registration failed: " + error.response.data);
      });
  };

  return (
    <form onSubmit={handleSubmit}>
      {/* Optional: if userId is needed, you can include this input field */}
      {/* <input type="text" name="userId" placeholder="User ID" value={user.userId} onChange={handleChange} /> */}

      <input
        type="text"
        name="userName"
        placeholder="Username"
        value={user.userName}
        onChange={handleChange}
        required
      />
      <input
        type="email"
        name="userEmail"
        placeholder="Email"
        value={user.userEmail}
        onChange={handleChange}
        required
      />
      <input
        type="text"
        name="userPhone"
        placeholder="Phone"
        value={user.userPhone}
        onChange={handleChange}
        required
      />
      <input
        type="password"
        name="userPassword"
        placeholder="Password"
        value={user.userPassword}
        onChange={handleChange}
        required
      />
      <button type="submit">Register</button>
    </form>
  );
};

export default Register;
